/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Fri Apr  4 13:11:14 2025
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_1 0.001
#define M_3 0.00625
#define M_4 0.083
#define M_5 0.188
#define M_6 0.083
#define M_7 0.1
#define M_8 0.041
#define M_9 0.083
#define M_10 0.188
#define M_11 0.083
#define M_12 0.1
#define M_13 0.041

// center of mass
#define L_2_1 0.0175
#define L_2_2 0.5475
#define L_2_3 0.05
#define L_3_4 0.012
#define L_3_5 -0.088625
#define L_3_6 0.012
#define L_3_7 -0.091625
#define L_3_8 -0.0045
#define L_3_9 0.012
#define L_3_10 -0.088625
#define L_3_11 0.012
#define L_3_12 -0.091625
#define L_3_13 -0.0045

// inertia
#define IN_1_3 5.26e-06
#define IN_5_3 1.3542e-06
#define IN_9_3 6.51e-06
#define IN_1_4 5.967e-05
#define IN_2_4 -8.14e-08
#define IN_3_4 1.308e-07
#define IN_5_4 5.688e-05
#define IN_6_4 -1.966e-06
#define IN_9_4 4.905e-05
#define IN_1_5 0.0002394
#define IN_5_5 0.0002394
#define IN_9_5 7.867e-06
#define IN_1_6 5.9855e-05
#define IN_2_6 -7.4698e-08
#define IN_3_6 1.208e-07
#define IN_5_6 5.707e-05
#define IN_6_6 -1.93e-06
#define IN_9_6 4.912e-05
#define IN_1_7 0.00021867
#define IN_5_7 0.00021867
#define IN_9_7 6.667e-06
#define IN_1_8 5.7434e-06
#define IN_5_8 1.7018e-05
#define IN_9_8 2.2208e-05
#define IN_1_9 5.967e-05
#define IN_2_9 -8.14e-08
#define IN_3_9 1.308e-07
#define IN_5_9 5.688e-05
#define IN_6_9 -1.966e-06
#define IN_9_9 4.905e-05
#define IN_1_10 0.0002394
#define IN_5_10 0.0002394
#define IN_9_10 7.867e-06
#define IN_1_11 5.9855e-05
#define IN_2_11 -7.4698e-08
#define IN_3_11 1.208e-07
#define IN_5_11 5.707e-05
#define IN_6_11 -1.93e-06
#define IN_9_11 4.912e-05
#define IN_1_12 0.00021867
#define IN_5_12 0.00021867
#define IN_9_12 6.667e-06
#define IN_1_13 5.7434e-06
#define IN_5_13 1.7018e-05
#define IN_9_13 2.2208e-05

// body point
#define DPT_3_1 0.4225
#define DPT_2_2 0.035
#define DPT_2_3 1.095
#define DPT_2_4 0.024
#define DPT_3_4 -0.04025
#define DPT_2_5 0.076
#define DPT_3_5 -0.04025
#define DPT_3_6 -0.20125
#define DPT_3_7 -0.172
#define DPT_1_8 0.035
#define DPT_2_8 0.02
#define DPT_3_8 -0.009
#define DPT_1_9 0.035
#define DPT_2_9 -0.02
#define DPT_3_9 -0.009
#define DPT_3_10 -0.009
#define DPT_1_11 -0.035
#define DPT_2_11 0.02
#define DPT_3_11 -0.009
#define DPT_1_12 -0.035
#define DPT_2_12 -0.02
#define DPT_3_12 -0.009
#define DPT_3_13 -0.20125
#define DPT_3_14 -0.172
#define DPT_1_15 -0.035
#define DPT_2_15 -0.02
#define DPT_3_15 -0.009
#define DPT_1_16 -0.035
#define DPT_2_16 0.02
#define DPT_3_16 -0.009
#define DPT_3_17 -0.009
#define DPT_1_18 0.035
#define DPT_2_18 0.02
#define DPT_3_18 -0.009
#define DPT_1_19 0.035
#define DPT_2_19 -0.02
#define DPT_3_19 -0.009

// ============================================================ //

# endif
