/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Fri Apr  4 13:11:14 2025
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define Tx_boom_id 1
#define Tz_boom_id 2
#define R_hip_id 3
#define T_lh_fixed_id 4
#define R_lh_id 5
#define T_lk_fixed_id 6
#define R_lk_id 7
#define R_lf_id 8
#define T_rh_fixed_id 9
#define R_rh_id 10
#define T_rk_fixed_id 11
#define R_rk_id 12
#define R_rf_id 13

static char *mbs_joints_name[] = {
	"ORIGIN",
	"Tx_boom",
	"Tz_boom",
	"R_hip",
	"T_lh_fixed",
	"R_lh",
	"T_lk_fixed",
	"R_lk",
	"R_lf",
	"T_rh_fixed",
	"R_rh",
	"T_rk_fixed",
	"R_rk",
	"R_rf"
	};

// body

#define Small_Link_Boom_id 1
#define Boom_id 2
#define Hip_id 3
#define Motor_l1_id 4
#define thigh_l_id 5
#define Motor_l2_id 6
#define leg_l_id 7
#define foot_l_id 8
#define Motor_r1_id 9
#define thigh_r_id 10
#define Motor_r2_id 11
#define leg_r_id 12
#define foot_r_id 13

static char *mbs_bodies_name[] = {
	"INVALID BODY ID : this is the base body 0",
	"Small_Link_Boom",
	"Boom",
	"Hip",
	"Motor_l1",
	"thigh_l",
	"Motor_l2",
	"leg_l",
	"foot_l",
	"Motor_r1",
	"thigh_r",
	"Motor_r2",
	"leg_r",
	"foot_r"
	};

// point

#define Body_0_Point_0_id 1
#define Small_Link_Boom_To_boom_id 2
#define Boom_To_hip_id 3
#define Hip_To_thigh_l_id 4
#define Hip_To_thigh_r_id 5
#define thigh_l_To_knee_l_id 6
#define leg_l_To_foot_l_id 7
#define foot_l_FS_AvD_l_id 8
#define foot_l_FS_AvG_l_id 9
#define foot_l_FS_M_l_id 10
#define foot_l_FS_ArD_l_id 11
#define foot_l_FS_ArG_l_id 12
#define thigh_r_To_knee_r_id 13
#define leg_r_To_foot_r_id 14
#define foot_r_FS_ArG_r_id 15
#define foot_r_FS_ArD_r_id 16
#define foot_r_FS_M_r_id 17
#define foot_r_FS_AvD_r_id 18
#define foot_r_FS_AvG_r_id 19

static char *mbs_points_name[] = {
	"ORIGIN",
	"Point_0 on body Body_0",
	"To_boom on body Small_Link_Boom",
	"To_hip on body Boom",
	"To_thigh_l on body Hip",
	"To_thigh_r on body Hip",
	"To_knee_l on body thigh_l",
	"To_foot_l on body leg_l",
	"FS_AvD_l on body foot_l",
	"FS_AvG_l on body foot_l",
	"FS_M_l on body foot_l",
	"FS_ArD_l on body foot_l",
	"FS_ArG_l on body foot_l",
	"To_knee_r on body thigh_r",
	"To_foot_r on body leg_r",
	"FS_ArG_r on body foot_r",
	"FS_ArD_r on body foot_r",
	"FS_M_r on body foot_r",
	"FS_AvD_r on body foot_r",
	"FS_AvG_r on body foot_r"
	};

// sensor


static char *mbs_sensors_name[] = {
	"INVALID SENSOR ID: 0"
	};

// extforce

#define F_AvD_L_id 1
#define F_AvG_L_id 2
#define F_Mid_L_id 3
#define F_ArD_L_id 4
#define F_ArG_L_id 5
#define F_ArG_R_id 6
#define F_ArD_R_id 7
#define F_Mid_R_id 8
#define F_AvD_R_id 9
#define F_AvG_R_id 10

static char *mbs_extforces_name[] = {
	"INVALID EXTFORCE ID: 0",
	"F_AvD_L",
	"F_AvG_L",
	"F_Mid_L",
	"F_ArD_L",
	"F_ArG_L",
	"F_ArG_R",
	"F_ArD_R",
	"F_Mid_R",
	"F_AvD_R",
	"F_AvG_R"
	};

// links



// links 3D



// Solids

// Balls

// Rods



// ============================================================ //

# endif
