/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Fri Apr  4 13:11:14 2025
 * --------------------------------------------------------
 *
 */
#include "mbs_path.h"
#include "user_model.h"
#include "mbs_binder_public.h"
#include "mbs_loader.h"
#include "useful_functions.h"
#include "mbs_message.h"
#include "lut.h"
#include <math.h>
#include <float.h>

// ============================================================ //


UserModel* mbs_new_user_model() 
{
    UserModel* um;
    um = (UserModel*)malloc(sizeof(UserModel));
    return um;
}

void mbs_delete_user_model(UserModel* um) 
{
    free(um);
}

 void mbs_load_user_model(MbsInfos* mbs_infos, UserModel* um) 
{
    int ind_state_value = 1;

}

 void mbs_bind_user_model(MbsInfos* mbs_infos, UserModel* um) 
{
}

void mbs_print_user_model(UserModel* um, FILE *fs)
{
    if (!fs)
    {
        fs = stdout;
    }

}
 
void mbs_get_user_model_size(int *n_user_model) 
{
    *n_user_model  = 0; 
}
 
void mbs_get_user_model_list(int *user_model_list) 
{

}

void mbs_save_um(FILE* stream, UserModel* um)
{
}

// ============================================================ //
 
